class MetaTraderSymbolInfo:
    def __init__(self, symbol_info):
        self.custom: bool = symbol_info.custom
        self.chart_mode:int = symbol_info.chart_mode
        self.select: bool = symbol_info.select
        self.visible: bool = symbol_info.visible
        self.session_deals:int = symbol_info.session_deals
        self.session_buy_orders:int = symbol_info.session_buy_orders
        self.session_sell_orders:int = symbol_info.session_sell_orders
        self.volume:int = symbol_info.volume
        self.volume_high:int = symbol_info.volumehigh
        self.volume_low:int = symbol_info.volumelow
        self.time:int = symbol_info.time
        self.digits:int = symbol_info.digits
        self.spread:int = symbol_info.spread
        self.spread_float: bool = symbol_info.spread_float
        self.ticks_book_depth:int = symbol_info.ticks_bookdepth
        self.trade_calc_mode:int = symbol_info.trade_calc_mode
        self.trade_mode:int = symbol_info.trade_mode
        self.start_time:int = symbol_info.start_time
        self.expiration_time:int = symbol_info.expiration_time
        self.trade_stops_level:int = symbol_info.trade_stops_level
        self.trade_freeze_level:int = symbol_info.trade_freeze_level
        self.trade_exe_mode:int = symbol_info.trade_exemode
        self.swap_mode:int = symbol_info.swap_mode
        self.swap_rollover3days:int = symbol_info.swap_rollover3days
        self.margin_hedged_use_leg: bool = symbol_info.margin_hedged_use_leg
        self.expiration_mode:int = symbol_info.expiration_mode
        self.filling_mode:int = symbol_info.filling_mode
        self.order_mode:int = symbol_info.order_mode
        self.order_gtc_mode:int = symbol_info.order_gtc_mode
        self.option_mode:int = symbol_info.option_mode
        self.option_right:int = symbol_info.option_right
        self.bid: float = symbol_info.bid
        self.bid_high: float = symbol_info.bidhigh
        self.bid_low: float = symbol_info.bidlow
        self.ask: float = symbol_info.ask
        self.ask_high: float = symbol_info.askhigh
        self.ask_low: float = symbol_info.asklow
        self.last: float = symbol_info.last
        self.last_high: float = symbol_info.lasthigh
        self.last_low: float = symbol_info.lastlow
        self.volume_real: float = symbol_info.volume_real
        self.volume_high_real: float = symbol_info.volumehigh_real
        self.volume_low_real: float = symbol_info.volumelow_real
        self.option_strike: float = symbol_info.option_strike
        self.point: float = symbol_info.point
        self.trade_tick_value: float = symbol_info.trade_tick_value
        self.trade_tick_value_profit: float = symbol_info.trade_tick_value_profit
        self.trade_tick_value_loss: float = symbol_info.trade_tick_value_loss
        self.trade_tick_size: float = symbol_info.trade_tick_size
        self.trade_contract_size: float = symbol_info.trade_contract_size
        self.trade_accrued_interest: float = symbol_info.trade_accrued_interest
        self.trade_face_value: float = symbol_info.trade_face_value
        self.trade_liquidity_rate: float = symbol_info.trade_liquidity_rate
        self.volume_min: float = symbol_info.volume_min
        self.volume_max: float = symbol_info.volume_max
        self.volume_step: float = symbol_info.volume_step
        self.volume_limit: float = symbol_info.volume_limit
        self.swap_long: float = symbol_info.swap_long
        self.swap_short: float = symbol_info.swap_short
        self.margin_initial: float = symbol_info.margin_initial
        self.margin_maintenance: float = symbol_info.margin_maintenance
        self.session_volume: float = symbol_info.session_volume
        self.session_turnover: float = symbol_info.session_turnover
        self.session_interest: float = symbol_info.session_interest
        self.session_buy_orders_volume: float = symbol_info.session_buy_orders_volume
        self.session_sell_orders_volume: float = symbol_info.session_sell_orders_volume
        self.session_open: float = symbol_info.session_open
        self.session_close: float = symbol_info.session_close
        self.session_aw: float = symbol_info.session_aw
        self.session_price_settlement: float = symbol_info.session_price_settlement
        self.session_price_limit_min: float = symbol_info.session_price_limit_min
        self.session_price_limit_max: float = symbol_info.session_price_limit_max
        self.margin_hedged: float = symbol_info.margin_hedged
        self.price_change: float = symbol_info.price_change
        self.price_volatility: float = symbol_info.price_volatility
        self.price_theoretical: float = symbol_info.price_theoretical
        self.price_greeks_delta: float = symbol_info.price_greeks_delta
        self.price_greeks_theta: float = symbol_info.price_greeks_theta
        self.price_greeks_gamma: float = symbol_info.price_greeks_gamma
        self.price_greeks_vega: float = symbol_info.price_greeks_vega
        self.price_greeks_rho: float = symbol_info.price_greeks_rho
        self.price_greeks_omega: float = symbol_info.price_greeks_omega
        self.price_sensitivity: float = symbol_info.price_sensitivity
        self.basis: str = symbol_info.basis
        self.category: str = symbol_info.category
        self.currency_base: str = symbol_info.currency_base
        self.currency_profit: str = symbol_info.currency_profit
        self.currency_margin: str = symbol_info.currency_margin
        self.bank: str = symbol_info.bank
        self.description: str = symbol_info.description
        self.exchange: str = symbol_info.exchange
        self.formula: str = symbol_info.formula
        self.isin: str = symbol_info.isin
        self.name: str = symbol_info.name
        self.page: str = symbol_info.page
        self.path: str = symbol_info.path
